### ISSUE TITLE
Errors in ICOB Agent during data load

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/indy-catalyst#424]
*aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer*
```
2020-01-08 21:30:06,527 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered
--
  | Traceback (most recent call last):
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message
  | endpoint, data=payload, headers=headers
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
  | self._resp = await self._coro
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
  | await resp.start(conn)
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 844, in start
  | message, payload = await self._protocol.read()  # type: ignore  # noqa
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/streams.py", line 588, in read
  | await self._waiter
  | aiohttp.client_exceptions.ServerDisconnectedError: None
  | 2020-01-08 21:30:24,713 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered
  | Traceback (most recent call last):
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message
  | endpoint, data=payload, headers=headers
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
  | self._resp = await self._coro
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
  | await resp.start(conn)
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 844, in start
  | message, payload = await self._protocol.read()  # type: ignore  # noqa
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/streams.py", line 588, in read
  | await self._waiter
  | aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```
*aiohttp.client_exceptions.ServerDisconnectedError: None*
```
2020-01-08 21:28:44,098 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered
--
  | Traceback (most recent call last):
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message
  | endpoint, data=payload, headers=headers
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
  | self._resp = await self._coro
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
  | await resp.start(conn)
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 844, in start
  | message, payload = await self._protocol.read()  # type: ignore  # noqa
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/streams.py", line 588, in read
  | await self._waiter
  | aiohttp.client_exceptions.ServerDisconnectedError: None
  | 2020-01-08 21:35:07,713 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered
  | Traceback (most recent call last):
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message
  | endpoint, data=payload, headers=headers
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
  | self._resp = await self._coro
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
  | await resp.start(conn)
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 844, in start
  | message, payload = await self._protocol.read()  # type: ignore  # noqa
  | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/streams.py", line 588, in read
  | await self._waiter
  | aiohttp.client_exceptions.ServerDisconnectedError: None
```

*_indy_loop_callback: Function returned error*
```
2020-01-08 21:41:22,530 indy.libindy WARNING _indy_loop_callback: Function returned error
--
  | 2020-01-08 21:41:22,595 indy.libindy WARNING _indy_loop_callback: Function returned error
  | 2020-01-08 21:41:40,041 indy.libindy WARNING _indy_loop_callback: Function returned error
  | 2020-01-08 21:42:13,117 indy.libindy WARNING _indy_loop_callback: Function returned error
```

*Cannot write to closing transport*
```
January 8th 2020, 00:15:36.061 | agent-indy-cat | 2020-01-08 08:15:36,060 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered
-- | -- | --

  | January 8th 2020, 00:15:36.061 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection

  | January 8th 2020, 00:15:36.061 | agent-indy-cat | await self._loop.create_connection(*args, **kwargs))

  | January 8th 2020, 00:15:36.061 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 794, in create_connection

  | January 8th 2020, 00:15:36.061 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 495, in _request

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | resp = await req.send(conn)

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 626, in send

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | await writer.write_headers(status_line, self.headers)

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/http_writer.py", line 112, in write_headers

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | self._write(buf)

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/http_writer.py", line 67, in _write

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | The above exception was the direct cause of the following exception:

  | January 8th 2020, 00:15:35.972 | agent-indy-cat |  

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | endpoint, data=payload, headers=headers

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 507, in _request

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | raise ClientOSError(*exc.args) from exc

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | aiohttp.client_exceptions.ClientOSError: Cannot write to closing transport

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | 2020-01-08 08:15:35,971 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | raise ConnectionResetError('Cannot write to closing transport')

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | ConnectionResetError: Cannot write to closing transport

  | January 8th 2020, 00:15:35.972 | agent-indy-cat |  

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message

  | January 8th 2020, 00:15:35.972 | agent-indy-cat | self._resp = await self._coro

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | ConnectionRefusedError: [Errno 111] Connect call failed ('172.50.23.210', 8080)

  | January 8th 2020, 00:15:35.954 | agent-indy-cat |  

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | The above exception was the direct cause of the following exception:

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | endpoint, data=payload, headers=headers

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | self._resp = await self._coro

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | timeout=real_timeout

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | return (yield from fut)

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | raise OSError(err, 'Connect call failed %s' % (address,))

  | January 8th 2020, 00:15:35.954 | agent-indy-cat |  

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | proto = await self._create_connection(req, traces, timeout)

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | req, traces, timeout)

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | raise last_exc

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | req=req, client_error=client_error)

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | raise client_error(req.connection_key, exc) from exc

  | January 8th 2020, 00:15:35.954 | agent-indy-cat | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api-indy-cat:8080 ssl:None [Connect call failed ('172.50.23.210', 8080)]

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | await self._loop.create_connection(*args, **kwargs))

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 794, in create_connection

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 781, in create_connection

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | 2020-01-08 08:15:35,953 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | raise exceptions[0]

  | January 8th 2020, 00:15:35.953 | agent-indy-cat | yield from self.sock_connect(sock, address)

  | January 8th 2020, 00:15:17.290 | agent-indy-cat | 2020-01-08 08:15:17,289 indy.libindy WARNING _indy_loop_callback: Function returned error
```
*[Errno 32] Broken pipe*
```
January 8th 2020, 02:43:27.240 | agent-indy-cat | 2020-01-08 10:43:27,239 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered
-- | -- | --

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | self._resp = await self._coro

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/streams.py", line 588, in read

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | await resp.start(conn)

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 844, in start

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | await self._waiter

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | endpoint, data=payload, headers=headers

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | message, payload = await self._protocol.read()  # type: ignore  # noqa

  | January 8th 2020, 02:43:27.240 | agent-indy-cat | aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | Traceback (most recent call last):

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | await self._loop.create_connection(*args, **kwargs))

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | raise exceptions[0]

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | yield from self.sock_connect(sock, address)

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb

  | January 8th 2020, 02:43:21.713 | agent-indy-cat |  

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | The above exception was the direct cause of the following exception:

  | January 8th 2020, 02:43:21.713 | agent-indy-cat |  

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 58, in handle_message

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | endpoint, data=payload, headers=headers

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | self._resp = await self._coro

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | timeout=real_timeout

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | req, traces, timeout)

  | January 8th 2020, 02:43:21.713 | agent-indy-cat | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection


```

**Comment by swcurran** [comment]
@WadeBarnes - I assume we can close this?  It's related to the verify process, correct?

Please reopen if necessary.
